/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as opErc721 from "./op-erc721";
export type { opErc721 };
export type { IERC20Test } from "./IERC20Test";
export type { TestERC1155 } from "./TestERC1155";
export type { TestERC20 } from "./TestERC20";
export type { TestERC721 } from "./TestERC721";
