/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testErc1155Sol from "./TestERC1155.sol";
export * as testErc721Sol from "./TestERC721.sol";
export { IERC20Test__factory } from "./IERC20Test__factory";
export { TestERC20__factory } from "./TestERC20__factory";
